apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: {{ .Values.spec.spec.containers.image }}:{{ .Values.spec.spec.containers.imagetag }}
        imagePullPolicy: IfNotPresent
        name: nginx
